### PR TITLE
Fix type package name erasure due to name collision

### LINKED ISSUE #4: Package names for types are removed on name collision
```go
package foo

import (
    "internal/foo"

type I interface {
	M() foo.T
}
```

Generates a mock as:

```go
func (i *I) M() (T) {
```

### PR DESCRIPTION
**Pull request by djui**
This does still not perfectly work for all cases (e.g. when the output file is in a different directory), but it should work better than the current implementation.

Fixes #4.

### CODE REVIEW

File: pkg/moq/moq.go [hunk 1]
```diff
@@ -69,6 +69,7 @@ type Mocker struct {
 	fset    *token.FileSet
 	pkgs    map[string]*ast.Package
 	pkgName string
+	pkgPath string
```
Comment (djui) [inline pkg/moq/moq.go]: **Motivation**: We store this package path globally so we don't have to compute it over and over again. It's the path related to the package provided by `src`.

File: pkg/moq/moq.go [hunk 2]
```diff
@@ -97,6 +98,12 @@ func New(src, packageName string) (*Mocker, error) {
 	if len(packageName) == 0 {
 		return nil, errors.New("failed to determine package name")
 	}
+	pkgPath, err := pkgPath(src)
+	if err != nil {
+		return nil, err
+	}
+	pkgPath = filepath.Join(filepath.Dir(pkgPath), packageName)
```
Comment (djui) [inline pkg/moq/moq.go]: **Motivation**: Since one is allowed to choose a different package name (`-pkg <name>`) we have to remove the latest path component and replace it with the provided one. Note that if no `packageName` was provided, it was deduced, this we just replace the exact same path component value. But that's neglectable.

File: pkg/moq/moq.go [hunk 3]
```diff
@@ -180,15 +188,12 @@ func (m *Mocker) Mock(w io.Writer, name ...string) error {
 }
 
 func (m *Mocker) packageQualifier(pkg *types.Package) string {
-	if m.pkgName == pkg.Name() {
+	path := pkg.Path()
```
Comment (djui) [inline pkg/moq/moq.go]: **Motivation**: Compare the entire package path from (1) in which package will the mock be against (2) from which package does the current type come from. If they differ, we need to leave the package classifier at the type and also add a new import statement. E.g.:

>https://github.com/betalo-sweden/moq/foo
>vs
>https://github.com/betalo-sweden/moq/bar
>->
>1 . add https://github.com/betalo-sweden/moq/bar as import
>2. leave bar for type qualifier, e.g. `bar.T`

>context
>vs
>https://github.com/betalo-sweden/moq/bar
>->
>remove/don't add any type qualifier.

File: pkg/moq/moq.go [hunk 4]
```diff
@@ -217,12 +222,10 @@ func (m *Mocker) extractArgs(sig *types.Signature, list *types.Tuple, nameFormat
 }
 
 func (*Mocker) pkgInfoFromPath(src string) (*loader.PackageInfo, error) {
-
-	abs, err := filepath.Abs(src)
+	pkgFull, err := pkgPath(src)
```
Comment (djui) [inline pkg/moq/moq.go]: **Motivation**: Just changed for DRY.

File: pkg/moq/moq.go [hunk 5]
```diff
@@ -323,6 +326,15 @@ var templateFuncs = template.FuncMap{
 	},
 }
 
+// pkgPath resolved the full package path from a source directory.
+func pkgPath(src string) (string, error) {
```
Comment (djui) [inline pkg/moq/moq.go]: **Motivation:** Just introduced for DRY.

File: pkg/moq/moq_test.go [hunk 6]
```diff
@@ -70,6 +70,32 @@ func TestMoqExplicitPackage(t *testing.T) {
...
+	var buf bytes.Buffer
+	err = m.Mock(&buf, "PersonStore")
+	if err != nil {
+		t.Errorf("m.Mock: %s", err)
+	}
+	s := buf.String()
+	// assertions of things that should be mentioned
+	var strs = []string{
+		"package same",
+		"CreateFunc func(ctx context.Context, person *same.Person, confirm bool) error",
```
Comment (djui) [inline pkg/moq/moq_test.go]: **Motivation:** The test tries to assert that the type `Person`, which exists in the package  `github.com/betalo-sweden/moq/pkg/moq/testpackages/samepackagename/same`, is not to be confused with a (non-existing) type in the package of subject: `github.com/betalo-sweden/moq/pkg/moq/testpackages/samepackagename`. Thus is should leave the `same` type qualifier.
